### ISSUE TITLE
Programmatic usage does not work. Fails on `niv.require`.

### ISSUE THREAD

**Issue by le0nik** [scott113341/npm-install-version#10]
This issue is in reply to this [comment](https://github.com/npm/npm/issues/5499#issuecomment-238107471).

1. Clone the minimal repro: https://github.com/le0nik/niv-webpack-repro/
2. Run `npm install`.
3. Run `npm test`.

The output in my case:

```sh
> niv-webpack-repro@1.0.0 test /Volumes/Workspace/niv-webpack-repro
> node index.js

Installed webpack@1.13.1 to node_modules/webpack@1.13.1
Installed webpack@2.1.0-beta.20 to node_modules/webpack@2.1.0-beta.20
module.js:442
    throw err;
    ^

Error: Cannot find module 'webpack@1.13.1'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object._require [as require] (/Volumes/Workspace/niv-webpack-repro/node_modules/npm-install-version/lib/require.js:9:10)
    at Object.<anonymous> (/Volumes/Workspace/niv-webpack-repro/index.js:6:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

Some more info:
- `$ npm -v`: `3.10.5`
- `$ node -v`: `v6.3.1`
- OS: `OSX El Capitan 10.11.6`

**Comment by scott113341** [comment]
Thanks @le0nik for the great bug report!  I figured out what was happening and it's all good now!  `v5.0.6` contains the fix 😄

**Comment by adiba** [comment]
@scott113341 Could you reopen this issue?  
For me it remains for any `version`:
```javascript
const niv = require('npm-install-version');
niv.install(`npm-install-version@${version}`);
niv.require(`npm-install-version@${version}`);
```
